services:
  app:    ##  サービス名
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile 
    environment:
      # .envから読み込んだ値をLaravelへ渡す
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
       - ./src/:/var/www/html
  
  web:    ##  サービス名
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile 
    ports:
      - 8081:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html

  db:   ##  サービス名
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
